#!/bin/sh

export UID=$(id -u)
export GID=$(id -g)
export USER=$(whoami)

IMAGE="publiocavalcante/php81"
docker build --build-arg UID="${UID}" \
      --build-arg GID="${GID}" \
      -t $IMAGE .

docker push $IMAGE
